extern "C" {
#include <all_baked_icon_fonts.h> // generated by CMake
}
#include <Icon_resources.hpp>


namespace cppgui {
    
    // TODO: use a CMake-generated preprocessor symbol instead of hardcoded array names (mainly because of size)

    auto Icon_resources::bell() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x39}; }

    auto Icon_resources::up_arrow() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x5D}; }

    auto Icon_resources::down_arrow() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x5B}; }

    auto Icon_resources::cross() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x58}; }

    auto Icon_resources::right_arrow() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x3E}; }

    auto Icon_resources::back() -> Glyph_specifier { return {fonts::get({modernpics_24}), 0x3C}; }

    auto Icon_resources::close() -> Glyph_specifier { return cross(); }

    // TODO: the following glyphs are actually not needed (yet) by CppGUI itself; move them to user project (LSInstruktor)

    auto Icon_resources::checkbox_empty() -> Glyph_specifier { return { fonts::get({symbola_hint_24}), 0x25A1 }; }

    auto Icon_resources::checkbox_checked() -> Glyph_specifier { return { fonts::get({symbola_hint_24}), 0x25A3 }; }

    auto Icon_resources::radiobutton_off() -> Glyph_specifier { return { fonts::get({symbola_hint_24}), 0x25CB }; }

    auto Icon_resources::radiobutton_on() -> Glyph_specifier { return { fonts::get({symbola_hint_24}), 0x25C9 }; }

} // ns cppgui